/**
 * 工程分析视图 —— 各工程 .cbp 重要属性（按工程分组），每个属性附带对应的 .cbp 配置片段
 *
 * - tooltip = 对应的 .cbp XML 片段（如 `<Option output="bin/Debug/app" />`）
 * - 点击属性行 = 在 .cbp 中定位对应配置（按候选文本搜索并高亮）
 * - 右键 = 「在 .cbp 中定位」/「复制 .cbp 片段」
 *
 * 数据由 extension 侧从已解析的 Project 模型汇总（零额外文件读取）后注入；本 provider 只负责渲染。
 */
import * as vscode from 'vscode';

/** 最近一次构建摘要（供分析视图展示） */
export interface LastBuildMeta {
  ok: boolean;
  durationMs: number;
  compiled: number;
  skipped: number;
  failed: number;
  errors: number;
  warnings: number;
}

/** 构建目标重要属性 */
export interface AnalysisTargetInfo {
  title: string;
  typeValue: number;
  typeLabel: string;
  compilerId: string;
  outputFilename: string;
  objectOutput: string;
  platformsLabel: string;
  compilerOptionCount: number;
  linkerOptionCount: number;
  linkLibCount: number;
  includeDirCount: number;
  preBuildCount: number;
  postBuildCount: number;
  externalDepsCount: number;
  /** 定位/片段用样本值（首项） */
  sampleCompilerOption?: string;
  sampleLinkerOption?: string;
  sampleLinkLib?: string;
  sampleIncludeDir?: string;
  samplePreBuild?: string;
  sampleExternalDep?: string;
}

/** 单个工程（.cbp）重要属性 */
export interface AnalysisProjectInfo {
  filename: string;
  title: string;
  dirName: string;
  compilerId: string;
  basePath: string;
  pchMode: number;
  pchLabel: string;
  objectNamingLabel: string;
  platformsLabel: string;
  fileCount: number;
  compileCount: number;
  linkCount: number;
  autoGeneratedCount: number;
  virtualFolderCount: number;
  customCommandFileCount: number;
  virtualTargets: { title: string; targets: string[] }[];
  targets: AnalysisTargetInfo[];
  cmd: {
    preBuild: number;
    postBuild: number;
    scriptCount: number;
    makefileCustom: boolean;
    makefile: string;
    executionDir: string;
  };
  dirs: { include: string[]; lib: string[]; resource: string[] };
  customVariables: { name: string; value: string }[];
  envVarCount: number;
  notes: string;
  /** 定位/片段用样本值（首项） */
  sampleFileName?: string;
  sampleScript?: string;
}

/** 工程分析数据（extension 侧计算） */
export interface AnalysisData {
  generatedAt: number;
  projects: AnalysisProjectInfo[];
  lastBuild?: LastBuildMeta;
}

class AnalysisNode extends vscode.TreeItem {
  /** 对应的 .cbp 片段（tooltip / 复制） */
  public xml?: string;
  /** 在 .cbp 中定位的候选文本（按顺序搜索首个命中） */
  public locate?: string[];

  constructor(
    label: string,
    collapsibleState: vscode.TreeItemCollapsibleState,
    public readonly children: AnalysisNode[] = [],
  ) {
    super(label, collapsibleState);
  }
}

/** 生成叶子节点；xml = .cbp 片段（tooltip + 右键复制），locate = 定位候选文本（点击定位） */
function leaf(
  label: string,
  description?: string,
  opts?: { xml?: string; locate?: string[] },
): AnalysisNode {
  const n = new AnalysisNode(label, vscode.TreeItemCollapsibleState.None);
  if (description !== undefined) n.description = description;
  if (opts?.xml) {
    n.xml = opts.xml;
    n.tooltip = opts.xml;
  }
  if (opts?.locate?.length) {
    n.locate = opts.locate;
    n.contextValue = 'analysisItem';
  }
  if (n.xml || n.locate) n.contextValue = 'analysisItem';
  return n;
}

/** 生成分组节点 */
function group(label: string, state: vscode.TreeItemCollapsibleState, children: AnalysisNode[] = []): AnalysisNode {
  return new AnalysisNode(label, state, children);
}

/** 截断长文本（备注首行摘要） */
function firstLine(text: string, max = 60): string {
  const line = text.split(/\r?\n/).find((l) => l.trim().length > 0) ?? '';
  return line.length > max ? line.slice(0, max) + '…' : line;
}

/** 定位候选：属性名=值 精确形式 + 值本身（提升命中率） */
function locateFor(attr: string, value?: string): string[] {
  const out: string[] = [];
  if (value !== undefined && value !== '') {
    out.push(`${attr}="${value}"`, `${attr}=`, value);
  } else {
    out.push(`${attr}=`);
  }
  return out;
}

/** 工程分析树 provider */
export class AnalysisTreeProvider implements vscode.TreeDataProvider<AnalysisNode> {
  private _onDidChangeTreeData = new vscode.EventEmitter<AnalysisNode | undefined>();
  readonly onDidChangeTreeData = this._onDidChangeTreeData.event;

  private data: AnalysisData | undefined;

  constructor(
    private readonly extensionUri: vscode.Uri,
    private readonly compute: () => AnalysisData,
  ) {}

  /** 彩色图标（resources/analysis-icons/*.svg） */
  private iconFile(name: string): vscode.Uri {
    return vscode.Uri.joinPath(this.extensionUri, 'resources', 'analysis-icons', name);
  }

  getTreeItem(element: AnalysisNode): vscode.TreeItem {
    return element;
  }

  getChildren(element?: AnalysisNode): AnalysisNode[] {
    if (element) return element.children;
    return this.buildRoot();
  }

  /** 失效缓存并刷新（下次 getChildren 时重算） */
  refresh(): void {
    this.data = undefined;
    this._onDidChangeTreeData.fire(undefined);
  }

  private getData(): AnalysisData {
    if (!this.data) {
      try {
        this.data = this.compute();
      } catch {
        this.data = { generatedAt: Date.now(), projects: [] };
      }
    }
    return this.data;
  }

  private buildRoot(): AnalysisNode[] {
    const d = this.getData();
    const nodes: AnalysisNode[] = [];

    // 顶部：最近构建快捷节点
    const lb = d.lastBuild;
    const lastBuildNode = leaf('最近构建');
    lastBuildNode.iconPath = this.iconFile('history.svg');
    if (lb) {
      lastBuildNode.description = `${lb.ok ? '成功' : '失败'} · ${(lb.durationMs / 1000).toFixed(1)}s`;
      lastBuildNode.tooltip = `编译 ${lb.compiled} · 跳过 ${lb.skipped} · 失败 ${lb.failed} · 错误 ${lb.errors} · 警告 ${lb.warnings}（点击打开 Build Log）`;
      lastBuildNode.command = { command: 'codeblocks.buildLog.focus', title: '打开 Build Log' };
    } else {
      lastBuildNode.description = '尚无构建记录';
    }
    nodes.push(lastBuildNode);

    if (!d.projects.length) {
      const empty = leaf('尚未打开工程', '(.cbp / .workspace)');
      empty.iconPath = this.iconFile('overview.svg');
      nodes.push(empty);
      return nodes;
    }

    // 默认全部折叠，仅第一个工程根 + 其概要展开
    d.projects.forEach((p, i) => nodes.push(this.buildProject(p, i === 0)));

    return nodes;
  }

  private buildProject(p: AnalysisProjectInfo, expanded: boolean): AnalysisNode {
    const root = new AnalysisNode(
      p.title,
      expanded ? vscode.TreeItemCollapsibleState.Expanded : vscode.TreeItemCollapsibleState.Collapsed,
    );
    root.iconPath = this.iconFile('project.svg');
    root.description = p.dirName;
    root.tooltip = `${p.filename}\n点击打开工程属性面板`;
    root.command = {
      command: 'codeblocks.projectProperties',
      title: '工程属性',
      arguments: [{ project: { filename: p.filename } }],
    };

    // 概要
    const overview = group(
      '概要',
      expanded ? vscode.TreeItemCollapsibleState.Expanded : vscode.TreeItemCollapsibleState.Collapsed,
      [
        leaf('工程文件', p.filename, {
          xml: `<Project title="${p.title}">`,
          locate: [`title="${p.title}"`, '<Project'],
        }),
        leaf('基路径', p.basePath, { xml: '（派生值：由 .cbp 所在目录计算，无对应配置）' }),
        leaf('默认编译器', p.compilerId, {
          xml: `<Option compiler="${p.compilerId}" />`,
          locate: locateFor('compiler', p.compilerId),
        }),
        leaf('平台', p.platformsLabel, {
          xml: `<Option platforms="${p.platformsLabel}" />`,
          locate: ['platforms='],
        }),
        leaf('PCH 模式', p.pchLabel, {
          xml: `<Option pch_mode="${p.pchMode}" />`,
          locate: locateFor('pch_mode'),
        }),
        leaf('对象命名', p.objectNamingLabel, {
          xml: `<Option extended_obj_names="1" />`,
          locate: ['extended_obj_names'],
        }),
        leaf('文件', `${p.fileCount}（编译 ${p.compileCount} / 链接 ${p.linkCount}）`, {
          xml: `<Unit filename="${p.sampleFileName ?? '…'}" />`,
          locate: ['<Unit filename=', p.sampleFileName ?? ''],
        }),
      ],
    );
    overview.iconPath = this.iconFile('overview.svg');
    overview.description = `编译器 ${p.compilerId} · 目标 ${p.targets.length} · 文件 ${p.fileCount}`;
    root.children.push(overview);

    // 构建目标
    const targetsGroup = group('构建目标', vscode.TreeItemCollapsibleState.Collapsed);
    targetsGroup.iconPath = this.iconFile('targets.svg');
    targetsGroup.description = `${p.targets.length} 个`;
    for (const t of p.targets) {
      const tn = new AnalysisNode(t.title, vscode.TreeItemCollapsibleState.Collapsed);
      tn.description = `${t.typeLabel} · ${t.outputFilename || '—'}`;
      tn.iconPath = this.iconFile('target.svg');
      tn.tooltip = `<Target title="${t.title}">`;
      tn.contextValue = 'analysisItem';
      tn.locate = [`<Target title="${t.title}"`, `title="${t.title}"`];
      const compilerDesc = t.compilerId && t.compilerId !== p.compilerId
        ? `${t.compilerId}（覆盖工程默认）`
        : (t.compilerId || '（同工程默认）');
      tn.children.push(
        leaf('类型', t.typeLabel, {
          xml: `<Option type="${t.typeValue}" />`,
          locate: locateFor('type', String(t.typeValue)),
        }),
        leaf('编译器', compilerDesc, {
          xml: `<Option compiler="${t.compilerId}" />`,
          locate: locateFor('compiler', t.compilerId),
        }),
        leaf('输出文件名', t.outputFilename || '（默认）', {
          xml: `<Option output="${t.outputFilename}" />`,
          locate: locateFor('output', t.outputFilename),
        }),
        leaf('对象目录', t.objectOutput || '（默认）', {
          xml: `<Option object_output="${t.objectOutput}" />`,
          locate: locateFor('object_output', t.objectOutput),
        }),
        leaf('平台', t.platformsLabel, {
          xml: `<Option platforms="${t.platformsLabel}" />`,
          locate: ['platforms='],
        }),
        leaf('编译选项', `${t.compilerOptionCount} 条`, {
          xml: `<Compiler>\n  <Add option="${t.sampleCompilerOption ?? '…'}" />\n  …共 ${t.compilerOptionCount} 条\n</Compiler>`,
          locate: locateFor('option', t.sampleCompilerOption),
        }),
        leaf('链接选项', `${t.linkerOptionCount} 条`, {
          xml: `<Linker>\n  <Add option="${t.sampleLinkerOption ?? '…'}" />\n  …共 ${t.linkerOptionCount} 条\n</Linker>`,
          locate: locateFor('option', t.sampleLinkerOption),
        }),
        leaf('链接库', `${t.linkLibCount} 个`, {
          xml: `<Linker>\n  <Add library="${t.sampleLinkLib ?? '…'}" />\n</Linker>`,
          locate: locateFor('library', t.sampleLinkLib),
        }),
        leaf('Include 目录', `${t.includeDirCount} 个`, {
          xml: `<Compiler>\n  <Add directory="${t.sampleIncludeDir ?? '…'}" />\n</Compiler>`,
          locate: locateFor('directory', t.sampleIncludeDir),
        }),
        leaf('pre-build / post-build', `${t.preBuildCount} / ${t.postBuildCount} 条`, {
          xml: `<ExtraCommands>\n  <Add before="${t.samplePreBuild ?? '…'}" />\n</ExtraCommands>`,
          locate: locateFor('before', t.samplePreBuild),
        }),
        leaf('外部依赖', `${t.externalDepsCount} 个`, {
          xml: `external_deps="${t.sampleExternalDep ?? '…'}"`,
          locate: locateFor('external_deps', t.sampleExternalDep),
        }),
      );
      targetsGroup.children.push(tn);
    }
    if (!targetsGroup.children.length) {
      targetsGroup.children.push(leaf('（无构建目标）'));
    }
    root.children.push(targetsGroup);

    // 构建命令
    const cmdGroup = group('构建命令', vscode.TreeItemCollapsibleState.Collapsed, [
      leaf('pre-build 命令', `${p.cmd.preBuild} 条`, {
        xml: '<ExtraCommands>\n  <Add before="…" />\n</ExtraCommands>',
        locate: ['<ExtraCommands', 'before='],
      }),
      leaf('post-build 命令', `${p.cmd.postBuild} 条`, {
        xml: '<ExtraCommands>\n  <Add after="…" />\n</ExtraCommands>',
        locate: ['after='],
      }),
      leaf('构建脚本', `${p.cmd.scriptCount} 个`, {
        xml: `file="${p.sampleScript ?? '…'}"`,
        locate: locateFor('file', p.sampleScript),
      }),
      leaf('makefile', p.cmd.makefileCustom ? `自定义：${p.cmd.makefile || 'Makefile'}` : '默认（非 makefile 模式）', {
        xml: `<Option makefile_is_custom="1" makefile="${p.cmd.makefile || 'Makefile'}" execution_dir="${p.cmd.executionDir}" />`,
        locate: ['makefile_is_custom', 'makefile=', 'execution_dir'],
      }),
      leaf('执行目录', p.cmd.executionDir || '（默认）', {
        xml: `execution_dir="${p.cmd.executionDir}"`,
        locate: locateFor('execution_dir', p.cmd.executionDir),
      }),
    ]);
    cmdGroup.iconPath = this.iconFile('commands.svg');
    cmdGroup.description = `pre ${p.cmd.preBuild} · post ${p.cmd.postBuild} · 脚本 ${p.cmd.scriptCount}`;
    root.children.push(cmdGroup);

    // 搜索目录
    const dirsGroup = group('搜索目录', vscode.TreeItemCollapsibleState.Collapsed);
    dirsGroup.iconPath = this.iconFile('dirs.svg');
    dirsGroup.description = `include ${p.dirs.include.length} · lib ${p.dirs.lib.length} · resource ${p.dirs.resource.length}`;
    const dirCategory = (label: string, list: string[]): AnalysisNode => {
      const g = group(label, vscode.TreeItemCollapsibleState.Collapsed);
      g.description = `${list.length} 个`;
      if (list.length) {
        for (const dir of list) {
          g.children.push(leaf(dir, undefined, {
            xml: `<Add directory="${dir}" />`,
            locate: locateFor('directory', dir),
          }));
        }
      } else {
        g.children.push(leaf('（空）'));
      }
      return g;
    };
    dirsGroup.children.push(
      dirCategory('include', p.dirs.include),
      dirCategory('lib', p.dirs.lib),
      dirCategory('resource', p.dirs.resource),
    );
    root.children.push(dirsGroup);

    // 文件
    const filesGroup = group('文件', vscode.TreeItemCollapsibleState.Collapsed, [
      leaf('编译 / 链接', `${p.compileCount} / ${p.linkCount}`, {
        xml: '<Unit filename="…">\n  <Option compile="1" link="1" />\n</Unit>',
        locate: ['<Unit filename=', 'compile=', 'link='],
      }),
      leaf('自动生成文件', `${p.autoGeneratedCount} 个`, {
        xml: 'auto_generated_by="…"',
        locate: ['auto_generated_by'],
      }),
      leaf('虚拟文件夹', `${p.virtualFolderCount} 个`, {
        xml: '<Option virtualFolders="…" />',
        locate: ['virtualFolders'],
      }),
      leaf('自定义构建命令文件', `${p.customCommandFileCount} 个`, {
        xml: '<Option buildCommand="…" />',
        locate: ['buildCommand='],
      }),
    ]);
    filesGroup.iconPath = this.iconFile('files.svg');
    filesGroup.description = `${p.fileCount} 个`;
    root.children.push(filesGroup);

    // 虚拟目标（有则显示）
    if (p.virtualTargets.length) {
      const vtGroup = group('虚拟目标', vscode.TreeItemCollapsibleState.Collapsed);
      vtGroup.iconPath = this.iconFile('vtargets.svg');
      vtGroup.description = `${p.virtualTargets.length} 个`;
      for (const vt of p.virtualTargets) {
        vtGroup.children.push(leaf(vt.title, `= ${vt.targets.join(';') || '（空）'}`, {
          xml: `<Add alias="${vt.title}" targets="${vt.targets.join(';')}" />`,
          locate: locateFor('alias', vt.title),
        }));
      }
      root.children.push(vtGroup);
    }

    // 变量（有则显示）
    if (p.customVariables.length || p.envVarCount) {
      const varsGroup = group('变量', vscode.TreeItemCollapsibleState.Collapsed);
      varsGroup.iconPath = this.iconFile('vars.svg');
      varsGroup.description = `自定义 ${p.customVariables.length} · 环境 ${p.envVarCount}`;
      for (const v of p.customVariables) {
        varsGroup.children.push(leaf(v.name, v.value, {
          xml: `<${v.name} value="${v.value}" />\n（Extensions → codeblocks_project_custom_variables）`,
          locate: [`${v.name} value="`, `${v.name}=`],
        }));
      }
      if (p.envVarCount) {
        varsGroup.children.push(leaf('环境变量', `${p.envVarCount} 个`, {
          xml: '<Environment>\n  <Variable name="…" value="…" />\n</Environment>',
          locate: ['<Environment>'],
        }));
      }
      root.children.push(varsGroup);
    }

    // 备注（有则显示）
    if (p.notes && p.notes.trim()) {
      const noteNode = leaf('备注', firstLine(p.notes), {
        xml: `<Notes>\n  <![CDATA[${firstLine(p.notes, 40)}]]>\n</Notes>`,
        locate: [firstLine(p.notes, 30)],
      });
      noteNode.iconPath = this.iconFile('note.svg');
      noteNode.tooltip = `${noteNode.xml}\n\n${p.notes}`;
      root.children.push(noteNode);
    }

    // 全部可定位节点：点击 = 在 .cbp 中定位（携带候选文本）
    const stamp = (n: AnalysisNode): void => {
      for (const c of n.children) {
        if (c.locate?.length && !c.command) {
          c.command = {
            command: 'codeblocks.analysis.locate',
            title: '在 .cbp 中定位',
            arguments: [{ filename: p.filename, locate: c.locate }],
          };
          if (!c.contextValue) c.contextValue = 'analysisItem';
        }
        stamp(c);
      }
    };
    stamp(root);

    return root;
  }
}
